//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gSamplerPoint                     sampler      NA          NA             s0      1 
// gAccumMap                         texture  float4          2d             t0      1 
// gRevealMap                        texture  float4          2d             t1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// Texcoord                 0   xy          0     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_input_ps linear v0.xy
dcl_output o0.xyzw
dcl_temps 2
sample_indexable(texture2d)(float,float,float,float) r0.x, v0.xyxx, t1.xyzw, s0
add r0.y, r0.x, l(-1.000000)
max r0.z, |r0.x|, l(1.000000)
mul r0.z, r0.z, l(0.000010)
ge r0.y, r0.z, |r0.y|
discard_nz r0.y
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, v0.xyxx, t0.xyzw, s0
max r0.y, r1.y, r1.x
max r0.y, r1.z, r0.y
and r0.y, r0.y, l(0x7fffffff)
ieq r0.y, r0.y, l(0x7f800000)
movc r0.yzw, r0.yyyy, r1.wwww, r1.xxyz
max r1.x, r1.w, l(0.000010)
div o0.xyz, r0.yzwy, r1.xxxx
add o0.w, -r0.x, l(1.000000)
ret 
// Approximately 16 instruction slots used
