//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbScreenSize
// {
//
//   int screenWidth;                   // Offset:    0 Size:     4
//   int screenHeight;                  // Offset:    4 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// defaultSS                         sampler      NA          NA             s0      1 
// singleColor                       texture  float4          2d             t0      1 
// cbScreenSize                      cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// Texcoord                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 5
itof r0.xy, cb0[0].xyxx
div r0.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r0.xyxx
mov r1.xy, -r0.xyxx
add r2.xy, r1.xyxx, v1.xyxx
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyxx, t0.xyzw, s0
mov r1.z, l(0)
add r1.xyzw, r1.zyxz, v1.xyxy
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, t0.xyzw, s0
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, r1.zwzz, t0.xyzw, s0
add r2.xyzw, -r2.xyzw, -r3.xyzw
mov r0.z, -r0.y
add r3.xyzw, r0.xzxy, v1.xyxy
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r3.xyxx, t0.xyzw, s0
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r3.zwzz, t0.xyzw, s0
add r2.xyzw, r2.xyzw, -r4.xyzw
add r1.xyzw, -r1.xyzw, r2.xyzw
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, v1.xyxx, t0.xyzw, s0
mad r1.xyzw, r2.xyzw, l(8.000000, 8.000000, 8.000000, 8.000000), r1.xyzw
mov r0.w, l(0)
add r2.xyzw, r0.xwwy, v1.xyxy
mad r0.xy, r0.xyxx, l(-1.000000, 1.000000, 0.000000, 0.000000), v1.xyxx
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.xyxx, t0.xyzw, s0
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r2.xyxx, t0.xyzw, s0
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.zwzz, t0.xyzw, s0
add r1.xyzw, r1.xyzw, -r4.xyzw
add r0.xyzw, -r0.xyzw, r1.xyzw
add r0.xyzw, -r2.xyzw, r0.xyzw
add r0.xyzw, -r3.xyzw, r0.xyzw
mul o0.xyzw, r0.xyzw, l(0.250000, 0.250000, 0.250000, 0.250000)
ret 
// Approximately 30 instruction slots used
