//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// Resource bind info for gParticleBuffer
// {
//
//   struct Particle
//   {
//       
//       float3 PositionW;              // Offset:    0
//       float Size;                    // Offset:   12
//       float3 Velocity;               // Offset:   16
//       float Rotation;                // Offset:   28
//       float4 StartColor;             // Offset:   32
//       float4 Color;                  // Offset:   48
//       float3 EmitterPosition;        // Offset:   64
//       float GravityModfier;          // Offset:   76
//       float LifeTime;                // Offset:   80
//       float Age;                     // Offset:   84
//
//   } $Element;                        // Offset:    0 Size:    88
//
// }
//
// Resource bind info for gIndexBuffer
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gParticleBuffer                   texture  struct         r/o             t0      1 
// gIndexBuffer                      texture  struct         r/o             t1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_VertexID              0   x           0   VERTID    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_structured t0, 88
dcl_resource_structured t1, 4
dcl_input_sgv v0.x, vertex_id
dcl_output o0.xyz
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_temps 2
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, v0.x, l(0), t1.xxxx
ld_structured_indexable(structured_buffer, stride=88)(mixed,mixed,mixed,mixed) r1.xyzw, r0.x, l(0), t0.xyzw
mov o0.xyz, r1.xyzx
ld_structured_indexable(structured_buffer, stride=88)(mixed,mixed,mixed,mixed) o1.xyzw, r0.x, l(48), t0.xyzw
ld_structured_indexable(structured_buffer, stride=88)(mixed,mixed,mixed,mixed) r1.z, r0.x, l(28), t0.xxxx
ld_structured_indexable(structured_buffer, stride=88)(mixed,mixed,mixed,mixed) r1.xy, r0.x, l(80), t0.xyxx
mov o2.xyzw, r1.yxzw
ret 
// Approximately 8 instruction slots used
