//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// Resource bind info for gParticleBuffer
// {
//
//   struct Particle
//   {
//       
//       float3 PositionW;              // Offset:    0
//       float Size;                    // Offset:   12
//       float3 Velocity;               // Offset:   16
//       float Rotation;                // Offset:   28
//       float4 StartColor;             // Offset:   32
//       float4 Color;                  // Offset:   48
//       float3 EmitterPosition;        // Offset:   64
//       float GravityModfier;          // Offset:   76
//       float LifeTime;                // Offset:   80
//       float Age;                     // Offset:   84
//
//   } $Element;                        // Offset:    0 Size:    88
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gParticleBuffer                       UAV  struct         r/w             u0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_uav_structured u0, 88
dcl_input vThreadID.x
dcl_thread_group 256, 1, 1
store_structured u0.xyzw, vThreadID.x, l(0), l(0,0,0,0)
store_structured u0.xyzw, vThreadID.x, l(16), l(0,0,0,0)
store_structured u0.xyzw, vThreadID.x, l(32), l(0,0,0,0)
store_structured u0.xyzw, vThreadID.x, l(48), l(0,0,0,0)
store_structured u0.xyzw, vThreadID.x, l(64), l(0,0,0,0)
store_structured u0.xy, vThreadID.x, l(80), l(0,0,0,0)
ret 
// Approximately 7 instruction slots used
